# fly.toml app configuration file generated for dreampad2 on 2023-06-07T10:11:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dreampad2"
primary_region = "waw"

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
